// Generated by https://quicktype.io

export interface IAuth {
    ID:        string;
    UsuarioID: string;
    Correo:    string;
    password:  string;
    web:       string;
    GitHub:    string;
}
