version: '3.8'
services:
  api:
    build: .
    environment:
      POSTGRES_USER: miguel
      POSTGRES_PASSWORD: usuario
      POSTGRES_DB: bdapicine
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      NODE_ENV: production
    ports:
      - 3000:3000
    depends_on:
      - db
  db:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_USER: miguel
      POSTGRES_PASSWORD: usuario
      POSTGRES_DB: bdapicine
    ports:
      - 5442:5432
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    depends_on:
      - api
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf